### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by alexreg** [foldericon/TXURLDumper#2]
I have cloned with all submodules, but I'm getting the following errors. They seem to be legitimate, since the file doesn't exist.

https://gist.github.com/3ef8696f86ca3af1d553

If I (hard) link in the `TextualApplication.h` file from the main Textual repository, I then get a different set of errors.

https://gist.github.com/c788d6235465ac34f72f

What's going on here? Is there any easy way to fix it? The `README` should probably have instructions on this in any case.

Thanks.

**Comment by foldericon** [comment]
see #3
